global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'finance-service'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['financeservice:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093